###################  项目启动端口  ###################
server:
  port: 18080

###################  spring配置  ###################
spring:
  
  resources:
    static-locations: classpath:/
  http:
    multipart:
      max-file-size: 30Mb 
      max-request-size: 30Mb
  servlet:
    multipart:
      max-file-size: 30Mb 
      max-request-size: 30Mb
  jackson:
    time-zone: GMT+8

